version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KAFKA_BROKER: kafka:9093
      MONGO_CONNECTION: mongodb://mongodb:27017
    depends_on:
      - kafka
      - mongodb
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_INSIDE: PLAINTEXT  # Especificando protocolo de segurança para INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_EXTERIOR: OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_OUTSIDE: PLAINTEXT  # Protocolo de segurança para OUTSIDE
      KAFKA_LISTENERS: OUTSIDE://0.0.0.0:9094
    ports:
      - "9093:9093"
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
